meta_product_name: "Coder's Learning Path"
meta_title: "Coder's Learning Path - Join our community and learn how to code for free with the best resources out there"
meta_description: "Coder's Learning Path provides learning experience tailored to your needs. Every learning path combines resources from all over the web to achieve a unique and well guided learning experience - for free. Get started today."
# meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
